const ValidationTypes = Object.freeze({
    AUTHENTICATION: "AUTHENTICATION",
    REQUIRED_NAME: "REQUIRED_NAME",
    REQUIRED_EMAIL: "REQUIRED_EMAIL",
    REQUIRED_PASSWORD: "REQUIRED_PASSWORD",
    REQUIRED_FIELDS: "REQUIRED_FIELDS"
});

export default ValidationTypes;